# Generated by Django 3.1.4 on 2020-12-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_buypass_buyticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buypass',
            name='concern',
        ),
        migrations.RemoveField(
            model_name='buyticket',
            name='concern',
        ),
        migrations.AlterField(
            model_name='buypass',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='buyticket',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
