# Generated by Django 3.1.4 on 2020-12-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201214_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='buypass',
            name='concern',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='buypass',
            name='duration',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='buyticket',
            name='concern',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='buyticket',
            name='stop1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='buyticket',
            name='stop2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='buypass',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='buyticket',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
