# Generated by Django 3.1.4 on 2020-12-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201215_0826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buypass',
        ),
        migrations.DeleteModel(
            name='Buyticket',
        ),
    ]
